AllCops:
  TargetRubyVersion: 2.3

Rails:
  Enabled: true

LineLength:
  Max: 127

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

MethodLength:
  Max: 45

ParameterLists:
  Max: 8

ClassAndModuleChildren:
  Enabled: false

Metrics/AbcSize:
  Max: 45

DotPosition:
  Enabled: false

Metrics/ClassLength:
  CountComments: false
  Max: 200
