---
version: 2
# log-file: /tmp/efm.log
# log-level: 1
tools:
  rubocop-lint: &rubocop-lint
    lint-command: 'rubocop --format emacs --force-exclusion --stdin ${INPUT}'
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m'
    root-markers:
      - Gemfile
      - Rakefile
      - .rubocop.yml
    commands:
      - command: 'rubocop --auto-correct-all ${INPUT}'
        title: 'rubocop fix'

  eslint-lint: &eslint-lint
    prefix: eslint
    lint-command: 'npx --no-install eslint -f unix --stdin --stdin-filename ${INPUT}'
    lint-ignore-exit-code: true
    lint-stdin: true
    root-markers:
      - package.json
      - .eslintrc.js
      - .eslintrc.yaml
      - .eslintrc.yml
      - .eslintrc.json
    commands:
      - title: 'eslint fix'
        command: npx
        arguments:
          - '--no-install'
          - 'eslint'
          - '--fix'
          - '${INPUT}'

  stylelint-lint: &stylelint-lint
    lint-command: 'npx stylelint --formatter unix --stdin --stdin-filename ${INPUT}'
    lint-ignore-exit-code: false
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m [%t%*[a-z]]'
    root-markers:
      - .stylelintrc.json
    commands:
      - command: 'npx stylelint --fix ${INPUT}'
        title: 'stylelint fix'

languages:
  javascript:
    - <<: *eslint-lint
  typescript:
    - <<: *eslint-lint
  ruby:
    - <<: *rubocop-lint
  css:
    - <<: *stylelint-lint
  scss:
    - <<: *stylelint-lint

...
