---
version: 2
# log-file: /tmp/efm.log
# log-level: 1
tools:
  rubocop-lint: &rubocop-lint
    lint-command: 'rubocop --format emacs --force-exclusion --stdin ${INPUT}'
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m'
    root-markers:
      - Gemfile
      - Rakefile
      - .rubocop.yml
    commands:
      - command: 'rubocop --auto-correct-all ${INPUT}'
        title: 'rubocop fix'

  tslint-lint: &tslint-lint
    lint-command: 'npx --no-install tslint --format msbuild ${INPUT}'
    lint-formats:
      - '%f(%l,%c): %trror%m'
    root-markers:
      - tslint.json
    commands:
      - command: 'npx --no-install tslint --fix ${INPUT}'
        title: 'tslint fix'

  stylelint-lint: &stylelint-lint
    lint-command: 'npx stylelint --formatter unix --stdin --stdin-filename ${INPUT}'
    lint-ignore-exit-code: false
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m [%t%*[a-z]]'
    root-markers:
      - .stylelintrc.json
    commands:
      - command: 'npx stylelint --fix ${INPUT}'
        title: 'stylelint fix'

languages:
  ruby:
    - <<: *rubocop-lint
  typescript:
    - <<: *tslint-lint
  css:
    - <<: *stylelint-lint
  scss:
    - <<: *stylelint-lint

...
