---
version: 2
tools:
  rubocop: &rubocop
    lint-command: bundle exec rubocop --format emacs --force-exclusion --stdin ${INPUT}
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m'
    format-command: bundle exec rubocop -A -f quiet --stderr -s ${INPUT}
    format-stdin: true
    root-markers:
      - Gemfile
      - Rakefile
      - .rubocop.yml

  javascript-eslint: &javascript-eslint
    prefix: eslint
    lint-command: npx --no-install eslint -f unix --stdin --stdin-filename ${INPUT}
    lint-ignore-exit-code: true
    lint-stdin: true
    root-markers:
      - package.json
      - .eslintrc.js
      - .eslintrc.yaml
      - .eslintrc.yml
      - .eslintrc.json

  prettier: &prettier
    format-command: npx --no-install prettier ${INPUT}
    format-stdin: true
    root-markers:
      - .prettierrc
      - .prettierrc.json
      - .prettierrc.js
      - .prettierrc.yml
      - .prettierrc.yaml
      - .prettierrc.json5
      - .prettierrc.mjs
      - .prettierrc.cjs
      - .prettierrc.toml

languages:
  ruby:
    - <<: *rubocop
  html:
    - <<: *prettier
  css:
    - <<: *prettier
  scss:
    - <<: *prettier
  json:
    - <<: *prettier
  javascript:
    - <<: *javascript-eslint
    - <<: *prettier
  typescript:
    - <<: *javascript-eslint
    - <<: *prettier
...
