general {
    after_sleep_cmd = hyprctl eval 'resume_displays()'
}

listener {
    timeout = 1200
    on-timeout = hyprctl eval 'suspend_displays()'
    on-resume = hyprctl eval 'resume_displays()'
}
