[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'coder/claudecode.nvim'
hook_add = '''
  let g:claudecode_auto_setup = {'auto_start': v:false}
  
  " VimEnterで確実に設定
  autocmd VimEnter * ++once nnoremap <silent> <leader>cc :ClaudeCode<CR>
  autocmd VimEnter * ++once nnoremap <silent> <leader>cf :ClaudeCodeFocus<CR>
  autocmd VimEnter * ++once nnoremap <silent> <leader>cr :ClaudeCode --resume<CR>
  autocmd VimEnter * ++once nnoremap <silent> <leader>cC :ClaudeCode --continue<CR>
  autocmd VimEnter * ++once nnoremap <silent> <leader>cb :ClaudeCodeAdd %<CR>
  autocmd VimEnter * ++once nnoremap <silent> <leader>cs :ClaudeCodeSend<CR>
  autocmd VimEnter * ++once nnoremap <silent> <leader>cs :ClaudeCodeTreeAdd<CR>
  autocmd VimEnter * ++once nnoremap <silent> <leader>ca :ClaudeCodeDiffAccept<CR>
  autocmd VimEnter * ++once nnoremap <silent> <leader>cd :ClaudeCodeDiffDeny<CR>
'''

[[plugins]]
repo = 'folke/snacks.nvim'

[[plugins]]
repo = 'github/copilot.vim'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'patstockwell/vim-monokai-tasty'

[[plugins]]
repo = 'posva/vim-vue'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'sheerun/vim-polyglot'
merged = 0

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-obsession'

[[plugins]]
repo = 'tpope/vim-rails'

[[plugins]]
repo = 'ver-1000000/angular-cli.vim'
rev = 'feature/page_extension_supports'
