[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'github/copilot.vim'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'patstockwell/vim-monokai-tasty'

[[plugins]]
repo = 'posva/vim-vue'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'sheerun/vim-polyglot'
merged = 0

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'tpope/vim-obsession'

[[plugins]]
repo = 'tpope/vim-rails'

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'ver-1000000/angular-cli.vim'
rev = 'feature/page_extension_supports'
